# config.py

# API Keys
COINWARZ_API_KEY = 'YOUR_COINWARZ_API_KEY'
COINAPI_API_KEY = 'YOUR_COINAPI_API_KEY'
DISCORD_BOT_TOKEN = 'YOUR_DISCORD_BOT_TOKEN'

# Paths
DATA_DIR = './data'
HISTORY_MONTHS = 6
